### PR TITLE
Fix multi-line diagnostic snippet

### LINKED ISSUE #25: Fix multiline diagnostic snippet
Since we are using a separate diagnostics printer for the playground, we should also fix this issue (https://github.com/ballerina-platform/ballerina-lang-go/issues/310) here. 
We need this fix: https://github.com/ballerina-platform/ballerina-lang-go/pull/316

### PR DESCRIPTION
**Pull request by snelusha**
## Purpose

Fixes #25

This pull request fixes multi-line diagnostic snippet rendering in the playground diagnostics printer by refactoring snippet layout and caret positioning logic so diagnostics that span multiple lines are rendered clearly and aligned.

Key changes
- diagnosticLocation now computes and stores a dynamic numWidth based on the start/end line numbers to enable correct line-number alignment for multi-line ranges.
- printSourceSnippet was refactored to render each affected line independently: it iterates from startLine to endLine, computes per-line start/end columns, prints a separate source line and pointer line for each, and aligns output using the computed numWidth.
- Caret/highlight logic was centralized into computeTrimmedCaretSpan which trims highlights to non-whitespace on a per-line basis, clamps columns to line boundaries, and produces correct highlight lengths (including zero-length highlights on all-whitespace lines).
- Pointer construction and output formatting were updated to use the trimmed per-line spans, improving accuracy of visual pointers and overall readability.

Impact
- Diagnostics that reference code spanning multiple lines are now displayed correctly and legibly in the playground, with proper alignment and per-line highlighting.

### CODE REVIEW

File: packages/wasm/diagnostics_printer.go [hunk 1]
```diff
@@ -51,20 +51,23 @@ type diagnosticLocation struct {
 	filePath            string
 	startLine, startCol int
 	endLine, endCol     int
-	lineNumStr          string
 	numWidth            int
 }
 
 func buildDiagnosticLocation(filePath string, startLine, startCol, endLine, endCol int) diagnosticLocation {
```
Comment (warunalakshitha) [inline packages/wasm/diagnostics_printer.go:57]: Can we directly use cli/utils methods in here, so any change will be applied here as well.

Comment (snelusha) [reply packages/wasm/diagnostics_printer.go:57]: Since `cli/utils` is in main package, we cannot reuse that directly here.

**Review by warunalakshitha — APPROVED** [review]
